/*

 * peripheral_config.h
 *
 *  Created on: 6 lis 2017
 *      Author: Kamil
 */

#ifndef PERIPHERAL_CONFIG_H_
#define PERIPHERAL_CONFIG_H_

/*
 *  Program zaimplementowany w oparciu o mikrokontroler AVR AtMega 328P
 *
 */

//USTAWIENIE MAKR DLA PRZYCISKU STARTOWEGO
#define PORTSTART PORTB
#define PINSTART PINB
#define KEYSTART (1<<PB0)

//USTAWIENIE MAKR DLA KRAÑCÓWEK SPRAWDZAJ¥CYCH POZYCJÊ R¥CZKI
#define PORT_KRANCOWKI PORTC
#define PIN_KRANCOWKI PINC
#define KEY_KRAN_START1 (1<<PC5) // R¥CZKA W POZYCJI STARTOWEJ
#define KEY_KRAN_START2 (1<<PC4)
#define KEY_KRAN_STOP1 (1<<PC3) // R¥CZKA W POZYCJI KOÑCZOWEJ
#define KEY_KRAN_STOP2 (1<<PC2)
#define KEY_KRAN_RACZKA1 (1<<PC1)  // R¥CZKA ZWARTA Z DRUTEM WIOD¥CYM
#define KEY_KRAN_RACZKA2 (1<<PC0)

//USTAWIENIE MAKR DLA WYJŒC NA MODU£ MUZYCZNY
#define MUSICDDR DDRD
#define MUSICPORT PORTD
#define MUSIC1 (1<<PD2)
#define MUSIC2 (1<<PD3)
#define MUSIC3 (1<<PD4)
#define MUSIC4 (1<<PD5)

//USTAWIENIE MAKR DLA BRZÊCZYKÓW
#define BUZZER_DDR DDRD
#define BUZZER_PORT PORTD
#define BUZZER1 (1<<PD0)
#define BUZZER2 (1<<PD1)


#endif /* PERIPHERAL_CONFIG_H_ */
